import { initialMessage } from "@/lib/data"; // Assuming this path is correct based on the image
import { createOpenAI } from "@ai-sdk/openai";
import { streamText } from "ai";

// Create an OpenAI client instance
const openai = createOpenAI({
  apiKey: process.env.OPENAI_API_KEY || "", // Using environment variable for API key
  compatibility: "strict", // Strict mode enabled
});

// Set the runtime for edge environments
export const runtime = "edge";

/**
 * Handles POST requests to the API route.
 * This function streams text generated by the OpenAI model.
 */
export async function POST(req: Request) {
  // Parse the incoming request body to get messages
  const { messages } = await req.json();

  // Stream text from the OpenAI model
  const stream = await streamText({
    model: openai("gpt-4o-mini"), // Using the specified GPT-4o-mini model
    messages: [initialMessage, ...messages], // Combining initial message with user messages
    temperature: 1, // Setting temperature for creativity
  });

  // Return the streamed response
  return stream.toDataStreamResponse();
}
